main:
  components_repository: "https://github.com/udacity/build-ml-pipeline-for-short-term-rental-prices#components"
  components_repository_fork: "https://github.com/Digital-Sherlock/build-ml-pipeline-for-short-term-rental-prices#components"
  # All the intermediate files will be copied to this directory at the end of the run.
  # Set this to null if you are running in prod
  project_name: nyc_airbnb
  experiment_name: development
  steps: all

etl:
  sample: "sample1.csv"
  min_price: 10 # dollars
  max_price: 350 # dollars

data_check:
  kl_threshold: 0.2
  
modeling:
  test_size: 0.2
  val_size: 0.2
  random_seed: 42
  stratify_by: "neighbourhood_group"
  # Maximum number of features to consider for the TFIDF applied to the title of the
  # insertion (the column called "name")
  max_tfidf_features: 30
  # RandomForestRegressor training parameters
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    n_jobs: -1
    criterion: squared_error
    max_features: 0.33
    oob_score: true
